# These are the device numbers of the board for the linear actuators and
# rack and pinion motor.
emcee:
    daisy:
        linear_actuators:
            arm_left: 0
            arm_right: 1
            bucket_left: 2
            bucket_right: 3
        pinions:
            left: 5
            right: 6
